kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.13
    commands:
      - GO11MODULE=on go test -mod=vendor ./...
  - name: config
    image: bitsbeats/drone-tree-config
    settings:
        GITHUB_TOKEN: ef4afbfb9effe8fb0a22ba7cf11f97c11c561106
