apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: micro-example
build:
  artifacts:
  - image: greeter/producer
    custom:
      buildCommand: make containerize SERVICE_DIR=cmd/greeter
      dependencies:
        paths:
          - ./cmd/greeter
          # - ./pkg
          - ./internal
          - ./proto
  - image: greeter/go-micro-consumer
    custom:
      buildCommand: make containerize SERVICE_DIR=cmd/consumers/go-micro
      dependencies:
        paths:
          - ./cmd/consumers/go-micro
          # - ./pkg
          - ./internal
          - ./proto
  - image: greeter/watermill-consumer
    custom:
      buildCommand: make containerize SERVICE_DIR=cmd/consumers/watermill
      dependencies:
        paths:
          - ./cmd/consumers/watermill
          # - ./pkg
          - ./internal
          - ./proto
deploy:
  kubectl:
    manifests:
    - cluster/namespace.yaml
    - cluster/zookeeper/*.yaml
    - cluster/kafka/*.yaml
    - cluster/kafka-manager/*.yml
    - cluster/cassandra/*.yaml
      #- cluster/kafka-monitor/*.yml // doesn't seem to work
    - cmd/greeter/k8s/local.yaml
    - cmd/consumers/go-micro/k8s/local.yaml
    - cmd/consumers/watermill/k8s/local.yaml
