apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: micro-example
build:
  artifacts:
  - image: greeter/producer
    context: cmd/greeter
    custom:
      buildCommand: make containerize 
      dependencies:
        paths:
          - .
          # - ../../../pkg
          - ../../internal
          - ../../proto
  - image: greeter/go-micro-consumer
    context: cmd/consumers/go-micro
    custom:
      buildCommand: make containerize 
      dependencies:
        paths:
          - .
          # - ../../../pkg
          - ../../../internal
          - ../../../proto
  - image: greeter/watermill-consumer
    context: cmd/consumers/watermill
    custom:
      buildCommand: make containerize
      dependencies:
        paths:
          - .
          # - ../../../pkg
          - ../../../internal
          - ../../../proto
deploy:
  kubectl:
    manifests:
    - cluster/namespace.yaml
    - cluster/zookeeper/*.yaml
    - cluster/kafka/*.yaml
    - cluster/kafka-manager/*.yml
      #- cluster/kafka-monitor/*.yml // doesn't seem to work
    - cmd/greeter/k8s/local.yaml
    - cmd/consumers/go-micro/k8s/local.yaml
    - cmd/consumers/watermill/k8s/local.yaml
