apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-watermill-consumer
  namespace: greeter-example
  labels:
    app: greeter-watermill-consumer
    kind: grpc 
    owner: ianthpun
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-watermill-consumer
      version: v1
  template:
    metadata:
      labels:
        app: greeter-watermill-consumer
        kind: grpc 
        owner: ianthpun
        version: v1
    spec:
      containers:
        - name: greeter-watermill-consumer
          image: greeter/watermill-consumer
          imagePullPolicy: IfNotPresent 
          ports:
          - name: micro-port 
            containerPort: 8080 
          env:
            - name: MICRO_SERVER_ADDRESS
              value: "0.0.0.0:8080"
            - name: MICRO_BROKER
              value: "kafka"
            - name: MICRO_BROKER_ADDRESS
              value: kafka:9092
