// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Reponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reponse) Reset()         { *m = Reponse{} }
func (m *Reponse) String() string { return proto.CompactTextString(m) }
func (*Reponse) ProtoMessage()    {}
func (*Reponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *Reponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reponse.Unmarshal(m, b)
}
func (m *Reponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reponse.Marshal(b, m, deterministic)
}
func (m *Reponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reponse.Merge(m, src)
}
func (m *Reponse) XXX_Size() int {
	return xxx_messageInfo_Reponse.Size(m)
}
func (m *Reponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Reponse.DiscardUnknown(m)
}

var xxx_messageInfo_Reponse proto.InternalMessageInfo

func (m *Reponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GreetEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEvent) Reset()         { *m = GreetEvent{} }
func (m *GreetEvent) String() string { return proto.CompactTextString(m) }
func (*GreetEvent) ProtoMessage()    {}
func (*GreetEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{3}
}

func (m *GreetEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEvent.Unmarshal(m, b)
}
func (m *GreetEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEvent.Marshal(b, m, deterministic)
}
func (m *GreetEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEvent.Merge(m, src)
}
func (m *GreetEvent) XXX_Size() int {
	return xxx_messageInfo_GreetEvent.Size(m)
}
func (m *GreetEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEvent proto.InternalMessageInfo

func (m *GreetEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GreetEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GreetedEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetedEvent) Reset()         { *m = GreetedEvent{} }
func (m *GreetedEvent) String() string { return proto.CompactTextString(m) }
func (*GreetedEvent) ProtoMessage()    {}
func (*GreetedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{4}
}

func (m *GreetedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetedEvent.Unmarshal(m, b)
}
func (m *GreetedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetedEvent.Marshal(b, m, deterministic)
}
func (m *GreetedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetedEvent.Merge(m, src)
}
func (m *GreetedEvent) XXX_Size() int {
	return xxx_messageInfo_GreetedEvent.Size(m)
}
func (m *GreetedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GreetedEvent proto.InternalMessageInfo

func (m *GreetedEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GreetedEvent) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*Reponse)(nil), "Reponse")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*GreetEvent)(nil), "GreetEvent")
	proto.RegisterType((*GreetedEvent)(nil), "GreetedEvent")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe6, 0x62, 0x77, 0xce, 0xcf,
	0xcd, 0x4d, 0xcc, 0x4b, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0x31, 0x95, 0x94, 0xb9, 0xd8, 0x83, 0x52, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85,
	0x24, 0xb8, 0xd8, 0x8b, 0x4b, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xc1, 0x0a, 0x38, 0x82, 0x60, 0x5c,
	0x25, 0x19, 0x2e, 0x8e, 0xa0, 0xd4, 0x62, 0x88, 0x2a, 0x4c, 0x23, 0xf4, 0xb8, 0xb8, 0xdc, 0x41,
	0x16, 0xba, 0x96, 0xa5, 0xe6, 0x95, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x40, 0xa5, 0x99, 0x32,
	0xe1, 0x56, 0x32, 0x21, 0xd4, 0x5b, 0x70, 0xf1, 0x80, 0xd5, 0xa7, 0xa6, 0x60, 0xd7, 0x81, 0xe4,
	0x0e, 0x26, 0x14, 0x77, 0x18, 0x19, 0x73, 0xb1, 0x43, 0x74, 0x16, 0x09, 0x69, 0x70, 0xf1, 0x83,
	0x99, 0x99, 0x79, 0xe9, 0x30, 0xcf, 0x71, 0xe8, 0x41, 0x59, 0x52, 0x9c, 0x7a, 0x30, 0xe7, 0x2a,
	0x31, 0x24, 0xb1, 0x81, 0x43, 0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x22, 0xb3, 0x22, 0x67,
	0x16, 0x01, 0x00, 0x00,
}
